// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "description": "Creates a padre/tutor account, optionally with one or more children in the\nsame request. A brand-new account always starts on the free plan, which\nallows at most 1 child (FR-007) — enforced server-side regardless of what\nthe client already validated. No login/password is accepted here (FR-009).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create an account (tutor + optional children)",
                "parameters": [
                    {
                        "description": "Account (and optional children) to create",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_account.createAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_account.accountResponse"
                        }
                    },
                    "400": {
                        "description": "Missing/invalid field, e.g. a malformed email or future birth date",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email already in use",
                        "schema": {
                            "$ref": "#/definitions/EmailConflictResponse"
                        }
                    },
                    "422": {
                        "description": "Free plan already has 1 child; upgrade required",
                        "schema": {
                            "$ref": "#/definitions/FreemiumLimitResponse"
                        }
                    },
                    "500": {
                        "description": "Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{accountId}": {
            "get": {
                "description": "Retrieves an account (tutor + children) by id, to populate the home page's\nchildren listing (FR-001). No authentication — the account id acts as a\nde facto access token, a deliberate continuation of the posture already\naccepted in specs/001/002 (see plan.md's privacy note).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get an account and its children",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account UUID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_account.accountResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists for this id",
                        "schema": {
                            "$ref": "#/definitions/AccountNotFoundResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{accountId}/children": {
            "post": {
                "description": "Adds a single child to an account already created, from the home page's\n\"Agregar hijo\" modal (FR-004). Applies the same field validation and\nfreemium 1-child limit as POST /accounts.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Add a child to an existing account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account UUID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Child to add",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_account.createChildRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_account.accountResponse"
                        }
                    },
                    "400": {
                        "description": "Missing/invalid field",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No account exists for this id",
                        "schema": {
                            "$ref": "#/definitions/AccountNotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "Free plan already has 1 child; upgrade required",
                        "schema": {
                            "$ref": "#/definitions/FreemiumLimitResponse"
                        }
                    }
                }
            }
        },
        "/catalog/countries": {
            "get": {
                "description": "Read-only catalog used to populate the país selector (contracts/get-catalog.md).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List countries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_catalog.countryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    }
                }
            }
        },
        "/catalog/countries/{countryCode}/states": {
            "get": {
                "description": "Used to populate the estado selector. Returns an empty array if the country\nhas no subdivisions in the catalog (contracts/get-catalog.md).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List states/provinces for a country",
                "parameters": [
                    {
                        "type": "string",
                        "example": "MX",
                        "description": "ISO country code",
                        "name": "countryCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_catalog.stateResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "countryCode not found in catalog",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Unexpected server error",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    }
                }
            }
        },
        "/children/{childId}/consultations": {
            "get": {
                "description": "Lists a child's medical consultations (date, doctor, symptoms and medication count), most recent first (FR-001).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consultations"
                ],
                "summary": "List a child's consultations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Child UUID",
                        "name": "childId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ConsultationListResponse"
                        }
                    },
                    "404": {
                        "description": "No child exists for this id",
                        "schema": {
                            "$ref": "#/definitions/ChildNotFoundResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registers a consultation with its prescription photo, medications and symptoms\n(FR-003, FR-004). At least one medication is required (FR-015), and each one needs\nits startTime (\"HH:MM\"): all of its doses are generated at once from it (research.md).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consultations"
                ],
                "summary": "Register a new medical consultation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Child UUID",
                        "name": "childId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Consultation to register",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_consultation.createConsultationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ConsultationDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Missing/invalid field",
                        "schema": {
                            "$ref": "#/definitions/ConsultationValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No child exists for this id",
                        "schema": {
                            "$ref": "#/definitions/ChildNotFoundResponse"
                        }
                    }
                }
            }
        },
        "/children/{childId}/overview": {
            "get": {
                "description": "Returns the doses scheduled in [from, to) (the parent's local \"today\"; the client\nsends the window because only it knows its timezone) and the treatment still\nrunning — the medication whose last scheduled dose is furthest ahead, derived only\nfrom the dose schedule. The window may not exceed 48 hours.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consultations"
                ],
                "summary": "A child's doses in a window and active treatment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Child UUID",
                        "name": "childId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2026-01-15T00:00:00-06:00",
                        "description": "Window start, RFC 3339",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2026-01-16T00:00:00-06:00",
                        "description": "Window end (exclusive), RFC 3339",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ChildOverviewResponse"
                        }
                    },
                    "400": {
                        "description": "Missing/invalid window",
                        "schema": {
                            "$ref": "#/definitions/ConsultationValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No child exists for this id",
                        "schema": {
                            "$ref": "#/definitions/ChildNotFoundResponse"
                        }
                    }
                }
            }
        },
        "/consultations/{consultationId}": {
            "get": {
                "description": "Retrieves the prescription photo, doctor, date, medications (with their doses,\nif any), and symptoms of a consultation (FR-013).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consultations"
                ],
                "summary": "Get a consultation's full detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consultation UUID",
                        "name": "consultationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ConsultationDetailResponse"
                        }
                    },
                    "404": {
                        "description": "No consultation exists for this id",
                        "schema": {
                            "$ref": "#/definitions/ConsultationNotFoundResponse"
                        }
                    }
                }
            }
        },
        "/consultations/{consultationId}/doses/{doseId}": {
            "patch": {
                "description": "Sets a dose's taken status. No validation of scheduled date or treatment\nstatus — a dose can be marked/unmarked at any time (FR-011, FR-016).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consultations"
                ],
                "summary": "Mark or unmark a dose as taken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consultation UUID",
                        "name": "consultationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Dose UUID",
                        "name": "doseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New taken status",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_consultation.updateDoseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DoseResponse"
                        }
                    },
                    "404": {
                        "description": "No dose exists for this id",
                        "schema": {
                            "$ref": "#/definitions/DoseNotFoundResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AccountNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "account_not_found"
                },
                "message": {
                    "type": "string",
                    "example": "Account not found"
                }
            }
        },
        "ActiveTreatmentResponse": {
            "type": "object",
            "properties": {
                "endsAt": {
                    "type": "string",
                    "example": "2026-01-18T22:00:00Z"
                },
                "medicationName": {
                    "type": "string",
                    "example": "Amoxicilina"
                },
                "otherCount": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "ChildNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "child_not_found"
                },
                "message": {
                    "type": "string",
                    "example": "Child not found"
                }
            }
        },
        "ChildOverviewResponse": {
            "type": "object",
            "properties": {
                "activeTreatment": {
                    "$ref": "#/definitions/ActiveTreatmentResponse"
                },
                "childId": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "doses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OverviewDoseResponse"
                    }
                }
            }
        },
        "ConsultationDetailResponse": {
            "type": "object",
            "properties": {
                "childId": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "consultDate": {
                    "type": "string",
                    "example": "2026-01-15"
                },
                "doctorName": {
                    "type": "string",
                    "example": "Dra. López"
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "medications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/MedicationResponse"
                    }
                },
                "photoBase64": {
                    "type": "string"
                },
                "symptoms": {
                    "type": "string",
                    "example": "Tos y fiebre leve"
                }
            }
        },
        "ConsultationFieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "doctorName"
                },
                "message": {
                    "type": "string",
                    "example": "doctor name is required"
                }
            }
        },
        "ConsultationListResponse": {
            "type": "object",
            "properties": {
                "childId": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "consultations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ConsultationSummaryResponse"
                    }
                }
            }
        },
        "ConsultationNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "consultation_not_found"
                },
                "message": {
                    "type": "string",
                    "example": "Consultation not found"
                }
            }
        },
        "ConsultationSummaryResponse": {
            "type": "object",
            "properties": {
                "consultDate": {
                    "type": "string",
                    "example": "2026-01-15"
                },
                "doctorName": {
                    "type": "string",
                    "example": "Dra. López"
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "medicationCount": {
                    "type": "integer",
                    "example": 2
                },
                "symptoms": {
                    "type": "string",
                    "example": "Tos y fiebre leve"
                }
            }
        },
        "ConsultationValidationErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ConsultationFieldError"
                    }
                },
                "error": {
                    "type": "string",
                    "example": "validation_error"
                },
                "message": {
                    "type": "string",
                    "example": "One or more fields are invalid"
                }
            }
        },
        "DoseNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "dose_not_found"
                },
                "message": {
                    "type": "string",
                    "example": "Dose not found"
                }
            }
        },
        "DoseResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "scheduledAt": {
                    "type": "string",
                    "example": "2026-01-15T08:00:00Z"
                },
                "taken": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "EmailConflictResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email_already_exists"
                },
                "message": {
                    "type": "string",
                    "example": "Email is already in use"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal_error"
                },
                "message": {
                    "type": "string",
                    "example": "Could not create account"
                }
            }
        },
        "FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "type": "string",
                    "example": "invalid email format"
                }
            }
        },
        "FreemiumLimitResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "freemium_child_limit_exceeded"
                },
                "limit": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "The free plan includes only one child per account"
                },
                "received": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "MedicationResponse": {
            "type": "object",
            "properties": {
                "doses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DoseResponse"
                    }
                },
                "durationDays": {
                    "type": "integer",
                    "example": 5
                },
                "frequencyHours": {
                    "type": "integer",
                    "example": 8
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "name": {
                    "type": "string",
                    "example": "Amoxicilina"
                },
                "startTime": {
                    "type": "string",
                    "example": "08:00"
                }
            }
        },
        "NotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "country_not_found"
                },
                "message": {
                    "type": "string",
                    "example": "Country not found in catalog"
                }
            }
        },
        "OverviewDoseResponse": {
            "type": "object",
            "properties": {
                "consultationId": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "medicationName": {
                    "type": "string",
                    "example": "Amoxicilina"
                },
                "scheduledAt": {
                    "type": "string",
                    "example": "2026-01-15T14:00:00Z"
                },
                "taken": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/FieldError"
                    }
                },
                "error": {
                    "type": "string",
                    "example": "validation_error"
                },
                "message": {
                    "type": "string",
                    "example": "One or more fields are invalid"
                }
            }
        },
        "internal_account.accountResponse": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_account.childResponse"
                    }
                },
                "countryCode": {
                    "type": "string",
                    "example": "MX"
                },
                "email": {
                    "type": "string",
                    "example": "ana@example.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "Ana"
                },
                "id": {
                    "type": "string",
                    "example": "e5f6a7b8-0000-0000-0000-000000000000"
                },
                "lastName": {
                    "type": "string",
                    "example": "Gómez"
                },
                "plan": {
                    "type": "string",
                    "example": "free"
                },
                "stateCode": {
                    "type": "string",
                    "example": "MX-JAL"
                }
            }
        },
        "internal_account.childResponse": {
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "example": "2020-01-15"
                },
                "firstName": {
                    "type": "string",
                    "example": "Luis"
                },
                "height": {
                    "type": "number",
                    "example": 95.5
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-0000-0000-0000-000000000000"
                },
                "lastName": {
                    "type": "string",
                    "example": "Gómez"
                },
                "weight": {
                    "type": "number",
                    "example": 14.2
                }
            }
        },
        "internal_account.createAccountRequest": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_account.createChildRequest"
                    }
                },
                "countryCode": {
                    "type": "string",
                    "example": "MX"
                },
                "email": {
                    "type": "string",
                    "example": "ana@example.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "Ana"
                },
                "lastName": {
                    "type": "string",
                    "example": "Gómez"
                },
                "stateCode": {
                    "type": "string",
                    "example": "MX-JAL"
                }
            }
        },
        "internal_account.createChildRequest": {
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "example": "2020-01-15"
                },
                "firstName": {
                    "type": "string",
                    "example": "Luis"
                },
                "height": {
                    "type": "number",
                    "example": 95.5
                },
                "lastName": {
                    "type": "string",
                    "example": "Gómez"
                },
                "weight": {
                    "type": "number",
                    "example": 14.2
                }
            }
        },
        "internal_catalog.countryResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "MX"
                },
                "name": {
                    "type": "string",
                    "example": "México"
                }
            }
        },
        "internal_catalog.stateResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "MX-JAL"
                },
                "name": {
                    "type": "string",
                    "example": "Jalisco"
                }
            }
        },
        "internal_consultation.createConsultationRequest": {
            "type": "object",
            "properties": {
                "consultDate": {
                    "type": "string",
                    "example": "2026-01-15"
                },
                "doctorName": {
                    "type": "string",
                    "example": "Dra. López"
                },
                "medications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_consultation.createMedicationRequest"
                    }
                },
                "photoBase64": {
                    "type": "string"
                },
                "symptoms": {
                    "type": "string",
                    "example": "Tos y fiebre leve"
                },
                "utcOffsetMinutes": {
                    "description": "UTCOffsetMinutes is the parent's UTC offset, so \"startTime\" is read in\ntheir own time zone. Optional: 0 (default) means UTC.",
                    "type": "integer",
                    "example": -360
                }
            }
        },
        "internal_consultation.createMedicationRequest": {
            "type": "object",
            "properties": {
                "durationDays": {
                    "type": "integer",
                    "example": 5
                },
                "frequencyHours": {
                    "type": "integer",
                    "example": 8
                },
                "name": {
                    "type": "string",
                    "example": "Amoxicilina"
                },
                "startTime": {
                    "type": "string",
                    "example": "08:00"
                }
            }
        },
        "internal_consultation.updateDoseRequest": {
            "type": "object",
            "properties": {
                "taken": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PediTrack API",
	Description:      "Backend API for account/children signup and the país/estado catalog.\nSee contracts/post-accounts.md and contracts/get-catalog.md under\nspecs/001-registro-cuenta-usuario/ for the source-of-truth prose contracts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
